# Generated by Django 3.2.4 on 2021-06-20 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_colab', models.CharField(max_length=100)),
                ('cpf', models.IntegerField(unique=True)),
                ('telefone', models.CharField(max_length=20)),
                ('endereco', models.CharField(max_length=100)),
                ('numero_casa', models.IntegerField()),
                ('bairro', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=50)),
                ('cep', models.IntegerField()),
                ('complemento', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('filial_nome', models.CharField(default='7004-Franca', max_length=50)),
            ],
            options={
                'verbose_name': 'Colaborador',
                'verbose_name_plural': 'Colaboradores',
            },
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eq_disponivel', models.BooleanField()),
                ('filial_nome', models.CharField(default='7004-Franca', max_length=50)),
                ('patrimonio', models.PositiveIntegerField()),
                ('modelo_equipamento', models.CharField(choices=[('1', 'Lenovo Thinkpad E490'), ('2', 'Lenovo Thinkpad E14'), ('3', 'Dell 3410'), ('4', 'Dell 3480'), ('5', 'Dell 3490')], max_length=50, verbose_name='Modelo')),
                ('processador', models.CharField(choices=[('1', 'i3'), ('2', 'i5'), ('3', 'i7'), ('4', 'i9'), ('5', 'M1')], max_length=50, verbose_name='Processador')),
                ('memoria', models.CharField(choices=[('1', '4GB'), ('2', '8GB'), ('3', '12GB'), ('4', '16GB'), ('5', '32GB')], max_length=50, verbose_name='Memória')),
                ('modo_entrega', models.CharField(choices=[('1', 'Retirada'), ('2', 'Correios'), ('3', 'Transportadora')], max_length=50, verbose_name='Modo de Envio')),
                ('status', models.CharField(choices=[('1', 'Aguardando separação'), ('2', 'Preparando'), ('3', 'Falta info do user'), ('4', 'Aguardando retirada'), ('5', 'Enviado a outra filial'), ('6', 'Concluído')], max_length=50, verbose_name='Status')),
                ('avaria', models.CharField(max_length=150, verbose_name='Avaria')),
                ('data_entrada', models.DateField(max_length=50, verbose_name='Data da entrada')),
            ],
            options={
                'verbose_name': 'Equipamento',
                'verbose_name_plural': 'Equipamentos',
            },
        ),
        migrations.CreateModel(
            name='Filial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filial_nome', models.CharField(default='7004-Franca', max_length=50)),
                ('filial_estoque', models.CharField(default=1, max_length=50, verbose_name='Filial')),
            ],
            options={
                'verbose_name': 'Filial',
                'verbose_name_plural': 'Filiais',
            },
        ),
        migrations.CreateModel(
            name='Motivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo_saida', models.CharField(choices=[('1', 'Descarte'), ('2', 'Manutenção'), ('3', 'Substituição'), ('4', 'Onboarding')], max_length=50, verbose_name='Motivo Saída')),
                ('filial_nome', models.CharField(default='7004-Franca', max_length=50)),
            ],
            options={
                'verbose_name': 'Motivo',
                'verbose_name_plural': 'Motivo',
            },
        ),
        migrations.CreateModel(
            name='Prestador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_prestador', models.CharField(max_length=100)),
                ('filial_nome', models.CharField(default='7004-Franca', max_length=50)),
            ],
            options={
                'verbose_name': 'Prestador',
                'verbose_name_plural': 'Prestadores',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50)),
                ('filial_nome', models.CharField(default='7004-Franca', max_length=50)),
                ('last_login', models.DateTimeField()),
                ('date_joined', models.DateTimeField()),
                ('dtchange_password', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='EntradaNovos',
            fields=[
                ('equipamento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.equipamento')),
                ('nota_fiscal', models.CharField(max_length=30, verbose_name='Nota Fiscal')),
            ],
            options={
                'verbose_name': 'Entrada Novo',
                'verbose_name_plural': 'Entradas de Novos Equipamentos',
            },
            bases=('core.equipamento',),
        ),
        migrations.CreateModel(
            name='EntradaOnboarding',
            fields=[
                ('equipamento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.equipamento')),
                ('nome_colaborador', models.CharField(max_length=50, verbose_name='Nome do colaborador')),
                ('id_colaborador', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Entrada Onboarding',
                'verbose_name_plural': 'Entradas de Onboarding',
            },
            bases=('core.equipamento',),
        ),
        migrations.CreateModel(
            name='EntradaSubstituicao',
            fields=[
                ('equipamento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.equipamento')),
                ('nome_colaborador', models.CharField(max_length=50, verbose_name='Nome do colaborador')),
                ('id_colaborador', models.IntegerField()),
                ('ticket', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Entrada Substituição',
                'verbose_name_plural': 'Entradas de Substituições',
            },
            bases=('core.equipamento',),
        ),
        migrations.CreateModel(
            name='OutDescarte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descreva brevemente')),
                ('filial_nome', models.CharField(default='7004-Franca', max_length=50)),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.equipamento')),
            ],
            options={
                'verbose_name': 'Descarte',
                'verbose_name_plural': 'Descartes',
            },
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_estoque', models.CharField(choices=[('1', 'Devol. Desligamento'), ('2', 'Devol. Substituição'), ('3', 'Novos'), ('4', 'DQS'), ('5', 'Imobilizado')], max_length=50, verbose_name='Tipo de Estoque')),
                ('filial_estoque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.filial')),
            ],
            options={
                'verbose_name': 'Estoque',
                'verbose_name_plural': 'Estoque',
            },
        ),
        migrations.AddField(
            model_name='equipamento',
            name='tipo_estoque',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.estoque'),
        ),
        migrations.CreateModel(
            name='OutSubstituicao',
            fields=[
                ('motivo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.motivo')),
                ('id_colab', models.IntegerField()),
                ('ticket', models.CharField(max_length=15)),
                ('patrimonio_devolvido', models.CharField(max_length=10, verbose_name='Patrimônio devolvido')),
                ('codigo_rastreio', models.CharField(blank=True, max_length=13)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.colaborador')),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.equipamento')),
            ],
            options={
                'verbose_name': 'Substituição',
                'verbose_name_plural': 'Substituições',
            },
            bases=('core.motivo',),
        ),
        migrations.CreateModel(
            name='OutOnboarding',
            fields=[
                ('motivo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.motivo')),
                ('id_vaga', models.IntegerField()),
                ('dt_integracao', models.DateField()),
                ('codigo_rastreio', models.CharField(blank=True, max_length=13)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.colaborador')),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.equipamento')),
            ],
            options={
                'verbose_name': 'Onboarding',
                'verbose_name_plural': 'Onboarding',
            },
            bases=('core.motivo',),
        ),
        migrations.CreateModel(
            name='OutManutencao',
            fields=[
                ('motivo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.motivo')),
                ('ordem_servico', models.PositiveIntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=7)),
                ('prestador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.prestador')),
            ],
            options={
                'verbose_name': 'Manutenção',
                'verbose_name_plural': 'Manutenções',
            },
            bases=('core.motivo',),
        ),
    ]
